name: weather_app
description: Flutter Weather App Example using the OpenWeatherMap API.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  http: ^0.13.0
  intl: ^0.18.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
